#cloud-config
# Adding grouops to the system

groups:
  - devops: [root, sys]
  - hashicorp

# Adding users to the system, Users are added after groups are added

users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCT+8e3HU3CPI4u9Ml6y9aaZ8JvlaOqP/iY10plxpiNXqqkaIC5J0ubE7my4tkic/2BWfPMevFRSTZkKmc3mXzBjHR28u+jLpQmJ2ig4YSWKUPB1KQ+kFDc+p5Nhtxy9d0HM29TOP6Gwf80NFhFJH25BwNwA2Ic4QKBhSrz6xBs2YqGsWkEvDY2jHwndhGTAsNGkedl0jxD51/YH/l1Qh5hYYqT9DqMPBo7s6S0/LSQbtDMnPWX5TV7xKcjF5Lc+wCRrRft0fiQJ4OA5frDW/2sH1CFxqYsTu7YlCUD5NIrF98HJkL5CuzmRPOCFd0SNcy6BbOFccoS+y0yS36yWE/


# Downloading and installing packages
packages:
  - httpd
  - docker 


# Running commands
runcmd:
  - sudo systemctl start httpd
  - sudo systemctl start docker
  - sudo usermod -aG docker ec2-user
  - sudo docker run -d -p 8080:80 nginx
